oauth2:
  user:
    github:
      client-id: 4e597e64bba6fcb0ed4a
      client-secret: ${abd3848b7049e00f3099444cf9865bfca2c78671}
      redirect-uri: http://localhost:8080/redirect/oauth
    google:
      client-id: 732481418367-3f84mu1hfof1fsiqeqn0ef2ekbab2e0p.apps.googleusercontent.com
      client-secret: ${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}
      redirect-uri: http://localhost:8080/redirect/oauth
  provider:
    github:
      token-uri: https://github.com/login/oauth/access_token
      user-info-uri: https://api.github.com/user
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
